Repository ChainSafe/chainbridge-solidity, pull requests merged in 2020-04, with the labels that each got.

#23 Whoswho
  contracts/Bridge.sol
  contracts/ERC20Safe.sol
  contracts/handlers/ERC20Handler.sol
  contracts/helpers/StringUtils.sol
  contracts/interfaces/IBridge.sol
  test/chainBridge/depositERC20.js
  test/chainBridge/voteDepositProposal.js
Labels: Status: Needs Review

#24 Update scripts
  .travis.yml
  scripts/cli/cmd/deployment.js
  scripts/cli/cmd/transfer.js
  scripts/cli/index.js
Labels: Status: Merge Ready

#25 Add data layout documentation to readme
  README.md
Labels: Status: Needs Review

#27 Test fix: Specify length of bytes in terms of number of bytes
  test/chainBridge/depositERC721.js
  test/chainBridge/depositGeneric.js
  test/chainBridge/voteDepositProposal.js
Labels: Status: Needs Review

#31 Add E2E ERC20 Same Chain Test
  contracts/ERC20Safe.sol
  contracts/handlers/ERC20Handler.sol
  test/e2eERC20.js
Labels: Status: Needs Review

#34 cent cli
  .travis.yml
  README.md
  contracts/Bridge.sol
  contracts/handlers/CentrifugeAssetHandler.sol
  scripts/cli/cmd/centrifuge.js
  scripts/cli/cmd/deployment.js
  scripts/cli/cmd/index.js
  scripts/cli/cmd/transfer.js
  scripts/cli/constants.js
  scripts/cli/index.js
Labels: Status: Needs Changes

#51 Optimize sol tests
  test/chainBridge/createDepositProposal.js
  test/chainBridge/depositERC20.js
  test/chainBridge/depositERC721.js
  test/chainBridge/voteDepositProposal.js
  test/e2eERC20.js
Labels: Status: Needs Review

#47 Add initialTokenIDs argument to ERC20Handler constructor
  contracts/Bridge.sol
  contracts/handlers/ERC20Handler.sol
  scripts/cli/cmd/deployment.js
  test/chainBridge/createDepositProposal.js
  test/chainBridge/depositERC20.js
  test/chainBridge/voteDepositProposal.js
  test/e2eERC20.js
  test/handlers/ERC20Handler/constructor.js
  test/handlers/ERC20Handler/setTokenIDAndContractAddress.js
Labels: Status: Needs Changes

#52 Rename tokenID to resourceID
  README.md
  contracts/handlers/ERC20Handler.sol
  contracts/handlers/ERC721Handler.sol
  contracts/handlers/GenericHandler.sol
  test/chainBridge/voteDepositProposal.js
  test/e2eERC20.js
  test/handlers/ERC20Handler/constructor.js
  test/handlers/ERC20Handler/setTokenIDAndContractAddress.js
Labels: Status: Needs Review

#48 Refactor CLI & extend functionality
  .travis.yml
  Makefile
  README.md
  scripts/cli/cmd/centrifuge.js
  scripts/cli/cmd/deploy.js
  scripts/cli/cmd/deployment.js
  scripts/cli/cmd/erc20.js
  scripts/cli/cmd/erc721.js
  scripts/cli/cmd/index.js
  scripts/cli/cmd/transfer.js
  scripts/cli/cmd/utils.js
  scripts/cli/constants.js
  scripts/cli/index.js
  scripts/cli/package-lock.json
  scripts/cli/package.json
  yarn.lock
Labels: Status: Needs Review

#58 Adds cost output to deploy
  scripts/cli/cmd/deploy.js
Labels: Status: Merge Ready

#54 E2E ERC20 Different Chains Deposit Mock
  test/e2e/erc20DifferentChainsMock.js
  test/e2e/erc20SameChain.js
Labels: Status: Merge Ready

#56 ERC20 Handler Contract Whitelist
  contracts/handlers/ERC20Handler.sol
  scripts/cli/cmd/deploy.js
  test/chainBridge/createDepositProposal.js
  test/chainBridge/depositERC20.js
  test/chainBridge/voteDepositProposal.js
  test/e2e/erc20DifferentChainsMock.js
  test/e2e/erc20SameChain.js
  test/handlers/ERC20Handler/constructor.js
  test/handlers/ERC20Handler/isWhitelisted.js
  test/handlers/ERC20Handler/setResourceIDAndContractAddress.js
Labels: Status: Merge Ready

#55 Sync Handlers, change resourceID to 32 bytes & supporting documentation
  README.md
  contracts/Bridge.sol
  contracts/handlers/CentrifugeAssetHandler.sol
  contracts/handlers/ERC20Handler.sol
  contracts/handlers/ERC721Handler.sol
  contracts/handlers/GenericHandler.sol
  contracts/interfaces/IBridge.sol
  contracts/interfaces/IDepositHandler.sol
  test/chainBridge/createDepositProposal.js
  test/chainBridge/depositERC20.js
  test/chainBridge/depositERC721.js
  test/chainBridge/depositGeneric.js
  test/chainBridge/voteDepositProposal.js
  test/e2e/erc20DifferentChainsMock.js
  test/e2e/erc20SameChain.js
  test/handlers/ERC20Handler/constructor.js
  test/handlers/ERC20Handler/isWhitelisted.js
  test/handlers/ERC20Handler/setResourceIDAndContractAddress.js
Labels: Status: Merge Ready

#66 Sync Relayer contract with Bridge
  contracts/Relayer.sol
  contracts/interfaces/IRelayer.sol
  test/contractBridge/createDepositProposal.js
  test/contractBridge/depositCentrifugeAsset.js
  test/contractBridge/depositERC20.js
  test/contractBridge/depositERC721.js
  test/contractBridge/depositGeneric.js
  test/contractBridge/voteDepositProposal.js
  test/contractRelayer/constructor.js
  test/contractRelayer/createRelayerThresholdProposal.js
  test/contractRelayer/getters.js
  test/contractRelayer/relayerProposal.js
  test/contractRelayer/voteRelayerThresholdProposal.js
Labels: Status: Needs Review

#67 ERC721 E2E Tests
  contracts/handlers/CentrifugeAssetHandler.sol
  contracts/handlers/ERC20Handler.sol
  contracts/handlers/ERC721Handler.sol
  test/e2e/erc20/erc20DifferentChainsMock.js
  test/e2e/erc20/erc20SameChain.js
  test/e2e/erc721/erc721DifferentChainsMock.js
  test/e2e/erc721/erc721SameChain.js
Labels: Status: Needs Review

#69 Add burnList to ERC20 and ERC721 Handlers
  contracts/ERC20Safe.sol
  contracts/ERC721Safe.sol
  contracts/erc/ERC20/ERC20Burnable.sol
  contracts/erc/ERC20/ERC20Mintable.sol
  contracts/handlers/ERC20Handler.sol
  contracts/handlers/ERC721Handler.sol
  scripts/cli/cmd/deploy.js
  test/contractBridge/createDepositProposal.js
  test/contractBridge/depositERC20.js
  test/contractBridge/depositERC721.js
  test/contractBridge/voteDepositProposal.js
  test/e2e/erc20/erc20DifferentChainsMock.js
  test/e2e/erc20/erc20SameChain.js
  test/e2e/erc721/erc721DifferentChainsMock.js
  test/e2e/erc721/erc721SameChain.js
  test/handlers/erc20/burnList.js
  test/handlers/erc20/constructor.js
  test/handlers/erc20/depositBurn.js
  test/handlers/erc20/isWhitelisted.js
  test/handlers/erc20/setResourceIDAndContractAddress.js
  test/handlers/erc721/burnList.js
  test/handlers/erc721/depositBurn.js
Labels: Status: Needs Review
